steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/brilliant-flame-475104-c2/facial-stress-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/brilliant-flame-475104-c2/facial-stress-api']
images:
  - 'gcr.io/brilliant-flame-475104-c2/facial-stress-api'
timeout: 1200s
